import type { Metadata } from "next";
import { Outfit } from "next/font/google"; // Import Outfit from next/font/google
import "./globals.css";
import Navbar from "@/components/Const/Navbar";
import Footer from "@/components/Const/Footer";
import FreelancerContextProvider from "@/Context/FreelancerContext";
import UserContextProvider from "@/Context/UserContext";

// Outfit font from Google Fonts
const outfit = Outfit({
  weight: ["400", "700"], // Choose the weights you want
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-outfit",
});

// Update metadata to include favicon from the public directory
export const metadata: Metadata = {
  title: "Freelance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FreelancerContextProvider>
        <UserContextProvider>
          <body className={`${outfit.variable} antialiased`}>
            <Navbar />

            <div className="max-w-screen-2xl px-6 py-4 mx-auto">
              <div className="mx-auto">{children}</div>
            </div>
            <Footer />
          </body>
        </UserContextProvider>
      </FreelancerContextProvider>
    </html>
  );
}
